### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Evertvdw** [deepscan/vscode-deepscan#1]
Hi there, gave this one a tryout but I'm behind a proxy and the connection fails: 

[Error - 08:03:39] Failed to inspect: connect ETIMEDOUT 52.34.95.71:443

Can't find how to setup a proxy for this add-on, is this possible?

**Comment by cimfalab** [comment]
Thanks for the reporting.
I think a proxy option for http request module should be set in our plugin.
After some investigation, I'll be back.

**Comment by cimfalab** [comment]
Dear,
I have modified to use the environment variable 'http_proxy' and it seemed to work nicely at least on Linux.
Are you using Linux and 'http_proxy' environment variable? If then, I will commit the change and publish a new plugin :)

**Comment by cimfalab** [comment]
I just published a 1.4.2 extension to the marketplace.
The updated version works as follows:
- It tries to use 'deepscan.proxy' option in user settings
- Then it tries to use 'http_proxy' environment variable

I hope this update will help you.
If you have a problem, kindly reopen this.

**Comment by Evertvdw** [comment]
Check, that did the trick!
