### ISSUE TITLE
REACT_USELESS_PROP_TYPES error shows even when i use prop types.

### ISSUE THREAD

**Issue by ishantdigitalgenius** [deepscan/vscode-deepscan#4]
I see `REACT_USELESS_PROP_TYPES` error even when i am using prop types.

```javascript
render () {
        return (<Template id={ this.props.id }/>
}

```
This works

```javascript
render () {
        const { props } = this;
        return (<Template id={ props.id }/>
}

```
This doesn't work.

**Comment by cimfalab** [comment]
Dear, thanks for your issue!
It seems to be our analyzer's bug for the destructuring pattern.
I'll discuss with my team and get back to you.

(We have a four-day weekend this week, so I'll be back next week. I appreciate your understanding.)

**Comment by cimfalab** [comment]
Dear @ishantdigitalgenius,
My colleague is working on this issue and the fix will be shipped in our next release scheduled at 02/23.
This is an issue of the analyzer in the server so you don't need to update the extension.
I will leave a comment when our release completes this week.

Have a good week!

**Comment by ishantdigitalgenius** [comment]
Thanks for the quick response. Looking forward to have this fixed 😄

**Comment by cimfalab** [comment]
We just updated deepscan.io with this fix.
Please check in your editor after re-opening or saving the file.

See our thank you [here](https://deepscan.io/docs/updates/2018-02/#thank-you).
And let me know if you still have a problem.

**Comment by ishantdigitalgenius** [comment]
I verified this and it works. Thanks a ton!
