### ISSUE TITLE
Deepscan fails to recognize type imports inside import statements

### ISSUE THREAD

**Issue by ImRodry** [deepscan/vscode-deepscan#43]
In TypeScript, you can have type imports in two different ways:
```ts
import type { Abc } from "module"
// or
import { Abc, type Def } from "module"
```
Both of these syntaxes are valid, however, Deepscan throws an error on the second one, saying `Unexpected token, expected ",".` and I believe this should be fixed

**Comment by ws807** [comment]
@ImRodry Thanks for reporting the issue!
You are right that `import { type ... }` is valid syntax. It is a new feature in TypeScript 4.5.
We will try to support it soon.

**Comment by ws807** [comment]
We just updated deepscan.io with this fix.
Please check in your editor after re-opening or saving the file.

Let me know if you still have a problem.

**Comment by ImRodry** [comment]
Can confirm it has been fixed. Thank you!
