### ISSUE TITLE
Shows unused import error for type when it's optionally used.

### ISSUE THREAD

**Issue by Bas950** [deepscan/vscode-deepscan#47]
![image](https://user-images.githubusercontent.com/34792838/180644574-3a6f334f-f6e7-4a2e-85da-c3dd9d7ea6fc.png)
![image](https://user-images.githubusercontent.com/34792838/180644585-5c472186-19bb-4f32-b646-1813ec68dcea.png)

Extension version: v1.53.1
[VSCode settings JSON](https://paste.gg/p/anonymous/0c99fa3f66aa42138bfb70a2dfbba25e)

**Comment by ws807** [comment]
@Bas950 Thanks for reporting the issue!

We will try to fix it soon.

**Comment by ws807** [comment]
We just updated deepscan.io with this fix.
Please check in your editor after re-opening or saving the file.

Let me know if you still have a problem.
