### ISSUE TITLE
[1.7.0] Not working for .ts files

### ISSUE THREAD

**Issue by NAlexandrov** [deepscan/vscode-deepscan#5]
Deepscan for .ts files was broken in 1.7.0:

<img width="1102" alt="deepscan" src="https://user-images.githubusercontent.com/157640/50490717-2a47a080-0a41-11e9-9b12-00262b19412c.png">

P.S. 1.6.2 works fine.

**Comment by cimfalab** [comment]
Dear @NAlexandrov,
Thanks for the issue.
It seems a bug the extension considers a .ts file as a .js file.
I am reviewing and will fix soon.

**Comment by cimfalab** [comment]
Hello, I just published a 1.7.1 extension.
There was a problem with the option 'deepscan.fileSuffixes' so .ts files were recognized as .js files.

Just update the extension.
Thank you and kindly reopen this issue if you have any problems.
