### ISSUE TITLE
Incorrect Syntax Error Reported for Nested Async Arrow Functions with Generic Type

### ISSUE THREAD

**Issue by paul-vd** [deepscan/vscode-deepscan#51]
Deepscan incorrectly identifies a syntax error when there are two nested async arrow functions, and the inner function has a generic type:

```
Unexpected token, expected ";".deepscan(SYNTAX_ERROR)
```

### Minimal Reproduction
```ts
type ASTNode = any;

async function createContext(request: Request) {
  return {
    body: request.body,
    req: request,
  };
}

const createGraphqlRequest = async (request: Request) => {
  const context = await createContext(request);

  return async <DocumentQuery extends ASTNode>(args: {  // <-- Error occurs here
    query: DocumentQuery;
  }) => {
    // DO SOMETHING ASYNC
    return context.body;
  };
};
```

However, both examples should be considered valid, as they are syntactically correct.

### Screenshot
![image](https://user-images.githubusercontent.com/39598117/229754852-a6e16505-374b-42bc-abb6-4013e794edec.png)

**Comment by ws807** [comment]
@paul-vd Thanks for reporting this issue.

We have published an update to fix this issue.
Please check in your editor after re-opening or saving the file.

Let me know if you still have problem.

**Comment by ayzyk** [comment]
I have the same problem, can you please help
<img width="1512" alt="Снимок экрана 2024-02-03 в 2 22 50 AM" src="https://github.com/deepscan/vscode-deepscan/assets/91569511/0c56fbac-9933-4a03-a990-920978e3d104">
