### ISSUE TITLE
Unexpected token, expected ";".deepscan(SYNTAX_ERROR). I have such a problem, can you please help

### ISSUE THREAD

**Issue by ayzyk** [deepscan/vscode-deepscan#52]
<img width="1512" alt="Снимок экрана 2024-02-03 в 2 22 50 AM" src="https://github.com/deepscan/vscode-deepscan/assets/91569511/286a6925-d077-4da8-a645-4df11243a5e3">

**Comment by ws807** [comment]
@ayzyk It seems that you have an extraneous closing parenthesis:

```js
btns.forEach((btn) =>{
    btn.addEventListener('click', (e)) => {
                                  // ^ This parenthesis incorrectly closes the addEventListener call
```

Please try removing the parenthesis and let me know if the problem persists.
